# Generated by Django 4.2.6 on 2023-10-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0004_video_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
